# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposal_apiary', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalApiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiary_title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_apiary', to='proposal_apiary.ProposalProxy')),
            ],
        ),
    ]
